### ISSUE TITLE
Enhance Navbar Responsiveness and Add a Responsive Carousel

### ISSUE THREAD

**Issue by CDT-PRATEEK** [iammadanlal/os_salon_web#13]
I would like to enhance the website by making the navbar responsive, so it works on all devices.

Additionally, we need to add an image carousel to make our content more engaging. These changes will improve the user experience and ensure our site looks great on various devices.

**Comment by inbuilt-aura** [comment]
hey,i am already working on this issue and will push pr today.Kindly close this issue.

**Comment by CDT-PRATEEK** [comment]
The Navbar I created is already merged. This is just a enhancement and an addition of carousel.
Have a great day !
