### ISSUE TITLE
UI improvement CSS , tailwind CSS 

### ISSUE THREAD

**Issue by MangalNathYadav** [iammadanlal/os_salon_web#2]
assign me for  designing ui and other pages in html and css. i am not that much advance in this but you can check some of my ui
https://mghacker.netlify.app [Landscape mode]

**Comment by iammadanlal** [comment]
I have clearly mentioned in the readme that you can come any feature and work on them. No need to ask for any assignment.

**Comment by MangalNathYadav** [comment]
any idea what should i make , is it anything?

**Comment by iammadanlal** [comment]
@MangalNathYadav Are you working on this?

**Comment by MangalNathYadav** [comment]
Yes but still need some more info , about layout and type of site like it's a barbar salon site na

**Comment by MangalNathYadav** [comment]
![image](https://github.com/iammadanlal/os_salon_web/assets/68454356/f0d2654c-8c41-4d42-bcce-7170b5caf643)
![image](https://github.com/iammadanlal/os_salon_web/assets/68454356/be83e531-119c-4817-920a-7cfb61dcc4b1)

basic template have been designed now i am working on ui.

**Comment by inbuilt-aura** [comment]
Hey @iammadanlal, is this repo hacktoberfest accepted?

**Comment by inbuilt-aura** [comment]
@
![Screenshot (54)](https://github.com/iammadanlal/os_salon_web/assets/74290697/6d0dd4a0-7761-4f37-861d-db479be78b7c)
MangalNathYadav, hey there is no code just a normal react app running.How you got the code and from wehre?

**Comment by MangalNathYadav** [comment]
> @ ![Screenshot (54)](https://user-images.githubusercontent.com/74290697/273145575-6d0dd4a0-7761-4f37-861d-db479be78b7c.png) MangalNathYadav, hey there is no code just a normal react app running.How you got the code and from wehre?

currently that code is not written by me, i have created in my local system. i have not the permssion to update the code

**Comment by inbuilt-aura** [comment]
@MangalNathYadav So like we can add any code here or what like how can I contribute?

**Comment by iammadanlal** [comment]
@inbuilt-aura You can refer to something like https://www.zoylee.com/ https://www.vagaro.com/ https://www.bookwell.com.au/ https://www.lixibox.com/. You can pick any part or feature and start building.

**Comment by iammadanlal** [comment]
> Hey @iammadanlal, is this repo hacktoberfest accepted?

yes

**Comment by MangalNathYadav** [comment]
> @MangalNathYadav So like we can add any code here or what like how can I contribute?

you can help with me in designing this site like i am deisinning index.html you start to design a shoping page for salon site
after completion we will merge both pages

**Comment by inbuilt-aura** [comment]
@MangalNathYadav, yeah we can do that but but share me the code then only and why are u designing index.html only,since it's a react code,we need to make accordingly to react not html css,we can make salon like let's contribute to one component at a time either me or you take Navbar and I will design that using tailwindcss.So,share me that code on which you are working ..

**Comment by MangalNathYadav** [comment]
> @MangalNathYadav, yeah we can do that but but share me the code then only and why are u designing index.html only,since it's a react code,we need to make accordingly to react not html css,we can make salon like let's contribute to one component at a time either me or you take Navbar and I will design that using tailwindcss.So,share me that code on which you are working ..

lets come over any other communication application for faster communication. then we can do together

**Comment by MangalNathYadav** [comment]
is it fine if i use tailwind css and html @iammadanlal 
willn't cause any trouble

**Comment by inbuilt-aura** [comment]
hello @iammadanlal, can you specify the techstacks which are required to build so that we can work on it or its same as written on label?

**Comment by inbuilt-aura** [comment]
@iammadanlal ?

**Comment by iammadanlal** [comment]
I have added label to this repo , sorry I have not added in readme. Only React, and styling or any other feature, you can use anything.

**Comment by iammadanlal** [comment]
@inbuilt-aura help @MangalNathYadav to convert the code into React. Or @MangalNathYadav You can make PR and then @inbuilt-aura can convert that into React components. What do you think guys?

**Comment by MangalNathYadav** [comment]
@iammadanlal thats great idea.

**Comment by MangalNathYadav** [comment]
![image](https://github.com/iammadanlal/os_salon_web/assets/68454356/d74485b3-f96d-46f2-bce7-45ec8fa89570)

I am designing prototype for website using canva. Then I and @inbuilt-aura  will start writing code for this
